Repository MedouneSGB/Waxtane, pull requests merged in 2022-10, with the labels that each got.

#36 add new word
  data/waxtane.csv
Labels: hacktoberfest

#37 bokk na
  data/waxtane.csv
Labels: hacktoberfest

#39 3 lignes ajoutées
  data/waxtane.csv
Labels: hacktoberfest, hackoberfest-accepted

#44 1 ligne ajoutée
  data/waxtane.csv
Labels: hacktoberfest, hackoberfest-accepted

#46 📝 docs(data): Waxtane update
  data/waxtane.csv
Labels: bug, hacktoberfest

#52 Readme and db spanish translations
  README.md
  data/news/word-2022-09-11-10-09.csv
  data/news/word-2022-09-12-16-35.csv
  data/waxtane.csv
Labels: hacktoberfest, hackoberfest-accepted

#62 Léebu wolof yi gëna siiw
  data/waxtane.csv
  package.json
Labels: hacktoberfest, hackoberfest-accepted

#63 Lowkeyboii contribution
  data/waxtane.csv
Labels: hacktoberfest, hackoberfest-accepted

#64 Add Data
  data/waxtane.csv
Labels: hacktoberfest, hackoberfest-accepted

#65 Reformat CSV file
  data/waxtane.csv
Labels: hacktoberfest, hackoberfest-accepted

#61 Catalan Translation
  data/waxtane.csv
Labels: hacktoberfest, hackoberfest-accepted
